name: mp23_astr
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  firebase_core: ^2.10.0
  firebase_database: ^10.1.1
  firebase_auth: ^4.4.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  mockito: ^5.4.0
  cloud_firestore: ^4.5.3
  firebase_storage: ^11.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
