// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChrbbew5zaQFosovYRv8s4yZ9la3rLkQw',
    appId: '1:46392923635:web:485b82ada27178a9d86e86',
    messagingSenderId: '46392923635',
    projectId: 'mp23-astr',
    authDomain: 'mp23-astr.firebaseapp.com',
    databaseURL: 'https://mp23-astr-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mp23-astr.appspot.com',
    measurementId: 'G-20FEL73KX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFPb3yOfkUI1eDwJXYp3Pvpa_UuTXYS_I',
    appId: '1:46392923635:android:659e0989e0f4d2e5d86e86',
    messagingSenderId: '46392923635',
    projectId: 'mp23-astr',
    databaseURL: 'https://mp23-astr-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mp23-astr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6jQXrX2y2uVD594lTnYwX-kTYKQ3_iO8',
    appId: '1:46392923635:ios:a12c2f4dfe763ef6d86e86',
    messagingSenderId: '46392923635',
    projectId: 'mp23-astr',
    databaseURL: 'https://mp23-astr-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mp23-astr.appspot.com',
    iosClientId: '46392923635-delts31a0m4tji8gr2ei2rduem5qud0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.mp23Astr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6jQXrX2y2uVD594lTnYwX-kTYKQ3_iO8',
    appId: '1:46392923635:ios:a12c2f4dfe763ef6d86e86',
    messagingSenderId: '46392923635',
    projectId: 'mp23-astr',
    databaseURL: 'https://mp23-astr-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mp23-astr.appspot.com',
    iosClientId: '46392923635-delts31a0m4tji8gr2ei2rduem5qud0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.mp23Astr',
  );
}
